### ISSUE TITLE
MissingPluginException on Android

### ISSUE THREAD

**Issue by nerddigestive** [rishab2113/cloud_speech#9]
Hi,

I am trying to use your plugin to implement Google Cloud Speech-to-Text functionality in my app. I have settled on your implementation as it is the only one that seems to support streaming audio to the API!

However, I am getting an error when I call `controller.intialize();` as in your example:

```
E/flutter (30377): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel cloud_speech)
E/flutter (30377): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter (30377): <asynchronous suspension>
E/flutter (30377): #1      AudioController.intialize (package:cloud_speech/cloud_speech.dart:95:22)
E/flutter (30377): <asynchronous suspension>
E/flutter (30377): #2      SpeechListener.initAudio (package:hepian_mobile/core/listen.dart:44:22)
E/flutter (30377): <asynchronous suspension>
E/flutter (30377): #3      new SpeechListener (package:hepian_mobile/core/listen.dart:18:5)
E/flutter (30377): #4      _HomePageState.build (package:hepian_mobile/pages/home_page.dart:46:17)
E/flutter (30377): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
E/flutter (30377): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
E/flutter (30377): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter (30377): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
E/flutter (30377): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
E/flutter (30377): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
E/flutter (30377): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter (30377): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter (30377): #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
E/flutter (30377): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
E/flutter (30377): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter (30377): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter (30377): #17     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
E/flutter (30377): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
E/flutter (30377): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
E/flutter (30377): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
E/flutter (30377): #21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
E/flutter (30377): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
E/flutter (30377): #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
E/flutter (30377): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
E/flutter (30377): #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
E/flutter (30377): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
E/flutter (30377): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter (30377): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter (30377): #29     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
E/flutter (30377): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
E/flutter (30377): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter (30377): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter (30377): #33     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
E/flutter (30377): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
E/flutter (30377): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter (30377): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter (30377): #37     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
E/flutter (30377): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
E/flutter (30377): #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
E/flutter (30377): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
E/flutter (30377): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter (30377): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter (30377): #43     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
E/flutter (30377): #44     _InheritedNotifierElement.update (package:flutter/src/widgets/in
```

Any thoughts as to what could be causing this?

I am running my app on Android, though I need support for both platforms.

**Comment by lewisccx** [comment]
have you solve this?
